openapi: "3.0.3"
info:
  title: "Radware Demo Store API"
  version: "1.0.0"
paths:
  /admin/dashboard:
    get:
      operationId: adminDashboard
      summary: Admin dashboard
  /users/11:
    get:
      operationId: getUser
      summary: Get user profile
    put:
      operationId: updateUser
      summary: Update user profile
  /users/12/orders:
    get:
      operationId: getUserOrders
      summary: Get user orders
  /admin/dashboar2d:
    get:
      operationId: adminDashboard
      summary: Admin dashboard
  /admin/users:
    get:
      operationId: adminListUsers
      summary: List all users
  /products:
    get:
      operationId: listProducts
      summary: List products
  /products/11:
    get:
      operationId: getProduct
      summary: Get product details
